# This is a test
---
- name: Deploy AS3 playbook
  hosts: localhost
  connection: local
  gather_facts: no
 
  vars:

  vars_files:
  - ../creds/autows_bigip_creds.yaml  

  tasks:
  - name: Deploy AS3 declaration
    uri:
      url: https://ec2-13-48-200-133.eu-north-1.compute.amazonaws.com/mgmt/shared/appsvcs/declare
      user: "{{bigip_user}}"
      password: "{{bigip_pass}}"
      method: POST
      body: "{{ lookup('file','./as3.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: as3_output

  - name: Debug AS3 as3_output
    debug:
      msg: "My AS3 output {{as3_output}}"
...